### PR TITLE
Encode select options

### PR DESCRIPTION
**Pull request by barryvdh**
Options are not encoded correctly.

### CODE REVIEW

**Comment by claar** [comment]
Much appreciated -- thanks @barryvdh

**Comment by claar** [comment]
I had to revert this due to backwards compatibility. This commit incorrectly converts characters in select labels such as `<` into HTML entities like `&lt;`, which is undesirable and breaks past behavior.

@barryvdh Can you speak to the original goal of this PR?

**Comment by barryvdh** [comment]
I think the use-case was XSS, for example a dropdown with user names like `Barry<script>alert('xss')</script>`

**Comment by claar** [comment]
Hmm.. I'm unsure how Former could protect against `<label>Barry<script>alert('xss')</script></label>` while also providing a mechanism for having a literal `>` in the label. 

I could be mistaken, but it seems that Former can't help here?

**Comment by barryvdh** [comment]
I'm not 100% sure, but I think it was when using a model query/collection as input, so not really easy to manually escape (or at least not really expected to be outputted raw), not sure what is best though.

**Comment by hillelcoren** [comment]
What about adding an `encode` method to Former::select to opt-in to the new behavior?

**Pull request merged**
