### PR TITLE
Add branch-alias

### PR DESCRIPTION
**Pull request by barryvdh**
So people can use `3.5.x@dev`

### CODE REVIEW

**Comment by tortuetorche** [comment]
Can you replace `"3.5-dev"` by `"3.5.x-dev"`, please?
Then I'll merged it.

**Comment by barryvdh** [comment]
Done

**Comment by tortuetorche** [comment]
Oups, can you also make a pull request for the `develop` branch, please?
I didn't check that it was for the `master` branch. Usually, We merged pull requests on the `develop` branch first, my bad.

**Comment by claar** [comment]
Actually, we don't want this patch in develop; the work flow I'm using for this project is that all common changes go into develop, then I do a simple merge into both master and 4.0 from develop. If a patch like this went into develop, it would break this workflow.

**Comment by tortuetorche** [comment]
@claar I agree with you, maybe what I said wasn't clear.
I meant that every pull requests had to be send to the `develop` branch and not directly to the `master` branch. And I don't think this patch is an exception for the workflow of this repository. IMO, the only kind of patches we can directly merge in the `master` branch should be only ones who fix some conflicts between `develop` and `master` branch. I see the `develop` branch like a security belt.

**Comment by claar** [comment]
@tortuetorche I guess I wasn't clear either :)

The master branch is currently our 3.x branch / Laravel 4 branch, and the 4.0 branch is our Laravel 5 branch. The develop branch is common to both branches.

Since this patch is adding a 3.x alias, it should go in master, not develop, as we would never want to merge this code into 4.0.

At least that's they way I've been using develop; if that's not standard or if you have a better suggestion, I'm more than open to it.

**Comment by tortuetorche** [comment]
In fact, it's not a problem if we merged this patch in the `4.0` branch. Nothing will break because the composer alias targeting only the `master` branch so the `4.0` would say "*Oh an alias for the `master` branch, fine but I don't care :wink:*" and that all.

**Comment by claar** [comment]
Ah, true. Kinda useless, but you're right. :)

**Pull request merged**
