### PR TITLE
Populate using models within an Eloquent\Collection

### PR DESCRIPTION
**Pull request by weotch**
Say you have a an Article model that is one-to-many with Images:

``` php
class Article {
  public function images() { return $this->hasMany('App\Image'); }
}
```

This PR allows you to populate a form using specific instances of that child.  For instance:

``` php
Former::populate(App\Article::first());
echo Former::text('images[2][title]');
```

This will look for the value of that field as if you did:

``` php
$article->images->find(2)->title
```

### CODE REVIEW

**Comment by weotch** [comment]
@claar Can you merge this in?  It's a pretty light change.

**Comment by claar** [comment]
Hey @weotch, sorry for the delay.

I believe this would introduce a backwards compatibility problem? `getAttributeFromModel()` already supports `Illuminate\Database\Eloquent\Collection` objects, because that's a subclass of `Illuminate\Support\Collection`.

So this PR would change the behavior of when an `Illuminate\Database\Eloquent\Collection` is passed in, no?

**Comment by weotch** [comment]
Yeah, it would, but I doubt users would have been using `getAttributeFromModel` in that way previously.  Such a person would have been trying to fetch a model instance from a collection by it's numerical index in the collection, which seems unlikely.

I think it more likely that someone is trying to get a model from a collection by whatever its key is (what `find()` does).

**Comment by claar** [comment]
With 150,000 installs of this package, I no longer doubt users. :)

To follow SemVer, technically we'd need to release this as "5.0.0", but that would be more of a pain than it's worth. I'm tempted to merge this into a "4.1.0" release, to at least let people opt-in to the new behavior if they have `~4.0` in their `composer.json` like I do.

I'd appreciate some community feedback, though.

**Comment by claar** [comment]
This is no longer mergeable due to the package rename -- feel free to submit a new patch if you can solve the backwards compatibility issues. Thanks, Robert!!

**Pull request closed without merging**
