### PR TITLE
Fix for regex rules

### PR DESCRIPTION
**Pull request by KuenzelIT**
Fixes issue #428

### CODE REVIEW

**Comment by tortuetorche** [comment]
Hi @KuenzelIT,

Thank you for this contribution!
Can you comment your code and also format it to be compatible with the PSR-2 Coding Standards, please?

Cheers,
Tortue Torche

**Comment by KuenzelIT** [comment]
I tried and hope it's correct.

What I don't get is why the new commit is automatically getting into this pull request?

**Comment by KuenzelIT** [comment]
I applied the fix in another file too. And it seems like PSR-2 wasn't applied there, thats why nearly every line is "changed".

The code there should be refactored but I don't feeld like I can do that without breaking anything else.

**Comment by tortuetorche** [comment]
Sorry, I thought Former followed the PSR-2 rules...

**Comment by tortuetorche** [comment]
@KuenzelIT I send you a pull request (KuenzelIT/former/pull/1) to keep some specific Former code formatting.
So if you merge it, it'll appear in this pull-request!

**Comment by KuenzelIT** [comment]
Done. Are you going to pull it into the main repo?

**Comment by claar** [comment]
@tortuetorche If the formatting of Former.php needs changed, can we please do it in a separate PR? I'm having trouble reviewing this PR as-is.

**Comment by tortuetorche** [comment]
> If the formatting of Former.php needs changed, can we please do it in a separate PR? I'm having trouble reviewing this PR as-is.

Done and it was exhausting! The `Field.php` file mix tabs and spaces.
I think it'll be a good thing if we follow the  PSR-2 <small>(or more)</small> Coding Standards like Laravel did.

**Pull request merged**
