### PR TITLE
Bootstrap 5 support

### PR DESCRIPTION
**Pull request by tortuetorche**
Reference: https://getbootstrap.com/docs/5.0/getting-started/introduction/

### Added
* Add Bootstrap 5 [floating labels](https://getbootstrap.com/docs/5.0/getting-started/introduction/) via the `floatingLabel()` method for `<input>`, `<select>` and `<textarea>` tags

  _NOTE: You need to use floating label elements with a `vertical_open` Former instance!_

  Usage with Laravel:
  ```blade
  {!! Former::vertical_open() !!}
      {!!
          Former::text('test-floating-label-ok')
              ->placeholder('dummy placeholder')
              ->floatingLabel()
      !!}
      {!!
          Former::select('users-floating-label')
              ->options(['User One', 'User Two', 'User Three'])
              ->placeholder('Select placeholder')
              ->floatingLabel()
      !!}
      {!!
          Former::textarea('textarea-floating-label')
              ->floatingLabel()
              ->placeholder('dummy placeholder')
      !!}
  {!! Former::close() !!}

  {!! Former::vertical_open() !!}
      <div class="row">
          <div class="col">
              {!!
                  Former::text('test-floating-label-one')
                      ->placeholder('dummy placeholder')
                      ->floatingLabel()
              !!}
          </div>
          <div class="col">
              {!!
                  Former::text('test-floating-label-two')
                      ->placeholder('dummy placeholder')
                      ->floatingLabel()
              !!}
          </div>
      </div>
  {!! Former::close() !!}
  ```
* Add the [switch](https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches) markup which is a custom checkbox for Bootstrap 5

  Some use cases with Laravel:
  ```blade
  {!!
      Former::switch('valid_switch_ok')
          ->text('Valid switch OK')
  !!}

  {!!
      Former::switches('valid_inline_switches_ok')
          ->switches('first', 'second', 'third', 'fourth')
          ->inline()
  !!}
  ```
* Add `removeGroupClass()` and `removeLabelClass()` methods

  Usage with Laravel:
  ```blade
  {!!
      Former::text('test')
          ->removeGroupClass('row')
          ->removeLabelClass('foo')
  !!}
  ```
  _**WARNING:** There is a bug in the HTMLObject package!_
  See my patch for more info: tortuetorche/html-object@b3c5601

### CODE REVIEW

**Comment by stayallive** [comment]
You did ping me once to check up on things... I seem to have ghosted that and cannot even find it anymore 😅

Anyway it's great you are putting work into B5 support and getting some much needed fixes in, thank you. As you've noticed I'm currently very low on bandwidth to deal with Former so I'm happy you do have some time for it, if you need anything ping me (again) and I'll see what I can do 👍

**Comment by tortuetorche** [comment]
Hi folks,

Here some news, this pull request need some tests for Bootstrap 5 [switch(es)](https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches) and [floating labels](https://getbootstrap.com/docs/5.0/forms/floating-labels/), then it should be ready for review!

Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
Ready for review 🎉

**Comment by stayallive** [comment]
This is a big PR, and I must admit I did not look too careful to be honest and I also don't have an app ready to test this on (not using BS5 myself at the moment). But from the quick skim through this looks pretty good to me! 💪

**Pull request merged**
