### PR TITLE
Configurable URL absolute or relative paths

### PR DESCRIPTION
**Pull request by gpassarelli**
Enabled relative URL support with config param and as a function param. Keeping the same behavior as Laravel `route` and `action` helper functions.
As a fallback, it keeps the original behavior of always returning absolute paths;

### CODE REVIEW

**Comment by hshahdoost** [comment]
Well I really needed this feature, How come it has not been confirmed?

**Comment by claar** [comment]
At first glance, this PR looks decent other than missing tests. @hshahdoost have you tested it and verified it's working well for you? Would you be willing and able to add tests?

**Comment by hshahdoost** [comment]
I have tried it, and it was working just fine, But since it wasn't in the library I took a different approach, I see if I can write tests for it.

**Comment by stayallive** [comment]
Hi @hshahdoost if you are still interested, I've merged the latest master changes so the tests will pass, will you still be able to add tests or is this feature no longer needed for you?

**Comment by stayallive** [comment]
Closing this PR because it is quite old and it has been a long time since there was any activity, if there is still interest please do re-open the PR!

**Pull request closed without merging**
