### PR TITLE
Fix and add new functionality

### PR DESCRIPTION
**Pull request by NelinD**
fix: Set value for once checkbox with name pattern 'name[x]'
fix: Set selected attr for select option where $value is integer and getAttribute('value') return numeric string

add: Create checkable group from query as select
About tests for new functionality... 
Calling the new method in a production environment in a test environment and gives different results.
I need help to write the tests.

### CODE REVIEW

**Comment by claar** [comment]
Thanks, Nelin. You'll need to rebase this off develop -- I can't tell which lines you've added and which were added by others.

**Comment by NelinD** [comment]
Not sure what happened.
But there are only visible change in my
alt

**Comment by NelinD** [comment]
All right?

**Comment by Anahkiasen** [comment]
Can you add a test for the functionality you added?

**Comment by NelinD** [comment]
No. Tests and the actual code give different results on the same input parameters.

**Comment by Anahkiasen** [comment]
Well maybe I can help you figure out what is going on in the test but I can't merge a feature without the insurance a subsequent PR or change in the codebase is not going to break it :p

**Comment by NelinD** [comment]
Good. I'll add tests and comments added to a specific description of the problem.

**Pull request closed without merging**
